# Generated by Django 5.1.4 on 2025-01-13 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='Ex.: 2025.1', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.student')),
            ],
        ),
        migrations.CreateModel(
            name='Socioeconomic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo')], max_length=50)),
                ('children', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('mode_transportation', models.CharField(choices=[('Carro', 'Carro'), ('Transporte público', 'Transporte público'), ('Caminhada', 'Caminhada'), ('Bicicleta', 'Bicicleta'), ('Outros', 'Outros')], max_length=50)),
                ('household_size', models.PositiveIntegerField()),
                ('annual_household_income', models.FloatField()),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollment')),
            ],
        ),
    ]
