# Generated by Django 5.1.4 on 2025-01-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='default_risk',
            field=models.CharField(blank=True, choices=[('Baixo', 'Baixo'), ('Médio', 'Médio'), ('Alto', 'Alto')], max_length=5, null=True),
        ),
    ]
