# Generated by Django 5.1.4 on 2025-01-26 12:40

from django.db import migrations

def add_professions(apps, schema_editor):
    Profession = apps.get_model('enrollment', 'Profession')
    professions = [
        "Architect",
        "Chef",
        "Civil Engineer",
        "Content Writer",
        "Digital Marketer",
        "Doctor",
        "Educational Consultant",
        "Entrepreneur",
        "Lawyer",
        "Manager",
        "Pharmacist",
        "Student",
        "Teacher",
        "UX/UI Designer",
    ]
    for profession in professions:
        Profession.objects.create(name=profession)


def remove_professions(apps, schema_editor):
    Profession = apps.get_model('enrollment', 'Profession')
    professions = [
        "Architect",
        "Chef",
        "Civil Engineer",
        "Content Writer",
        "Digital Marketer",
        "Doctor",
        "Educational Consultant",
        "Entrepreneur",
        "Lawyer",
        "Manager",
        "Pharmacist",
        "Student",
        "Teacher",
        "UX/UI Designer",
    ]
    for profession in professions:
        Profession.objects.filter(name=profession).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_professions, remove_professions),
    ]
