# Generated by Django 5.1.4 on 2025-01-26 21:08

from django.db import migrations

def add_degree(apps, schema_editor):
    Degree = apps.get_model('enrollment', 'Degree')
    degrees = [
        "B.Arch",
        "B.Com",
        "B.Ed",
        "B.Pharm",
        "B.Tech",
        "BA",
        "BBA",
        "BCA",
        "BE",
        "BHM",
        "BSc",
        "Class 12",
        "LLB",
        "LLM",
        "M.Com",
        "M.Ed",
        "M.Pharm",
        "M.Tech",
        "MA",
        "MBA",
        "MBBS",
        "MCA",
        "MD",
        "ME",
        "MHM",
        "MSc",
        "Others",
        "PhD"
    ]
    for degree in degrees:
         Degree.objects.create(name=degree)


def remove_degree(apps, schema_editor):
    Degree = apps.get_model('enrollment', 'Degree')
    degrees = [
        "B.Arch",
        "B.Com",
        "B.Ed",
        "B.Pharm",
        "B.Tech",
        "BA",
        "BBA",
        "BCA",
        "BE",
        "BHM",
        "BSc",
        "Class 12",
        "LLB",
        "LLM",
        "M.Com",
        "M.Ed",
        "M.Pharm",
        "M.Tech",
        "MA",
        "MBA",
        "MBBS",
        "MCA",
        "MD",
        "ME",
        "MHM",
        "MSc",
        "Others",
        "PhD"
    ]
    for degree in degrees:
        Degree.objects.filter(name=degree).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_auto_20250126_1246'),
    ]

    operations = [
        migrations.RunPython(add_degree, remove_degree),
    ]
