# Generated by Django 5.1.4 on 2025-01-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_auto_20250126_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='financial_strees',
            new_name='financial_stress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='risk_of_drepession',
        ),
        migrations.AddField(
            model_name='student',
            name='risk_of_depression',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
