# Generated by Django 5.1.4 on 2025-01-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_rename_financial_strees_student_financial_stress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Masculino'), ('Female', 'Feminino')], max_length=50),
        ),
    ]
