# Generated by Django 5.1.4 on 2025-02-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.FloatField()),
                ('city', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('academic_pressure', models.FloatField()),
                ('work_pressure', models.FloatField()),
                ('cgpa', models.FloatField()),
                ('study_satisfaction', models.FloatField()),
                ('job_satisfaction', models.FloatField()),
                ('sleep_duration', models.CharField(max_length=50)),
                ('dietary_habits', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('suicidal_thoughts', models.CharField(max_length=10)),
                ('work_study_hour', models.FloatField()),
                ('financial_stress', models.FloatField()),
                ('family_history_mental_illness', models.CharField(max_length=10)),
                ('depression', models.IntegerField()),
            ],
        ),
    ]
