# Generated by Django 5.1.4 on 2025-02-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdata',
            name='academic_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='depression',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='dietary_habits',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='family_history_mental_illness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='financial_stress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='job_satisfaction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='sleep_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='study_satisfaction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='suicidal_thoughts',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='work_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='work_study_hour',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
